### ISSUE TITLE
class VistDataLoader do not include forward()

### ISSUE THREAD

**Issue by Acwy** [JunjieHu/ReCo-RL#1]
File "/home/ReCo-RL/src/trainer.py", line 58, in _forward
    lprobs = self.model(sample['src_seq'], sample['src_lengths'], sample['trg_seq'])
 In vist_dataloader.py, there are not 'def forward()' in 'class VistDataLoader'. Can you submit a new code that include the 'forward' method?

**Comment by JunjieHu** [comment]
Sorry for missing this message. I just updated the trainer. It should be fixed now!
