### ISSUE TITLE
The preprocessed data and pre-trained models

### ISSUE THREAD

**Issue by gujinjing** [JunjieHu/ReCo-RL#2]
Thank you for your sharing, but the links of the preprocessed data and pre-trained models are not available. Could you please send me an available link? Thank you very much!

**Comment by JunjieHu** [comment]
Hi, could you try this [link](https://drive.google.com/drive/folders/1j8P6CwykJDAIV6Et7bci_x00mvBAwmVm?usp=sharing)?

**Comment by gujinjing** [comment]
I tried but still can't open it. Can you send me a link to Baidu-Netdisk? Thanks a lot.

**Comment by JunjieHu** [comment]
I just confirmed with others and they can open the Google drive link. I guess that you should use a VPN to access to Google Drive if you're in China. It's pretty slow to upload something to Baidu cloud in the US, but I may try it later.

**Comment by gujinjing** [comment]
Thank you very much for your reply!

**Comment by JunjieHu** [comment]
Hi I uploaded to Baidu Cloud.
Link: https://pan.baidu.com/s/1Y2cII5W7_F0mEkXo_XQ_yA 
Code: qeas
