### ISSUE TITLE
image preprocessing scripts

### ISSUE THREAD

**Issue by arnavkapoor** [JunjieHu/ReCo-RL#3]
Hi, I was looking to evaluate the model on some of the image in the VIST data and other images in my curated dataset as well. Would it be possible for you to share the image pre-processing scripts that were used to 
a) Resize / Transform the raw image.  
b) Get the Resnet 152 Features.
i.e steps to get the resnet image features from say this raw image -> https://ibb.co/qxjgTtZ

I had experimented with multiple transformation to (256,256) and then getting the features etc , I also tried the AREL image processing script -> https://github.com/eric-xw/AREL/blob/master/scripts/extract_features.py but wasn't able to get the same values. Would really appreciate any pointers. 
PS :- Thanks a lot for making the code public.

**Comment by vmurahari3** [comment]
Did you figure this out?

**Comment by JunjieHu** [comment]
Sorry that I use the extracted feature from https://github.com/eric-xw/AREL. I would recommend you to ask the original paper for preparing the images!
